/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CabangRouteImport } from './routes/cabang'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AdminTimRouteImport } from './routes/admin.tim'
import { Route as AdminTestimoniRouteImport } from './routes/admin.testimoni'
import { Route as AdminPromoRouteImport } from './routes/admin.promo'
import { Route as AdminProdukRouteImport } from './routes/admin.produk'
import { Route as AdminPesanRouteImport } from './routes/admin.pesan'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLayananRouteImport } from './routes/admin.layanan'
import { Route as AdminKategoriArtikelRouteImport } from './routes/admin.kategori-artikel'
import { Route as AdminKategoriRouteImport } from './routes/admin.kategori'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminCabangRouteImport } from './routes/admin.cabang'
import { Route as AdminArtikelRouteImport } from './routes/admin.artikel'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CabangRoute = CabangRouteImport.update({
  id: '/cabang',
  path: '/cabang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimRoute = AdminTimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniRoute = AdminTestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukRoute = AdminProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesanRoute = AdminPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayananRoute = AdminLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategoriArtikelRoute = AdminKategoriArtikelRouteImport.update({
  id: '/kategori-artikel',
  path: '/kategori-artikel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategoriRoute = AdminKategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCabangRoute = AdminCabangRouteImport.update({
  id: '/cabang',
  path: '/cabang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cabang': typeof CabangRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/promo': typeof PromoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/cabang': typeof AdminCabangRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/kategori-artikel': typeof AdminKategoriArtikelRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/tim': typeof AdminTimRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cabang': typeof CabangRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/promo': typeof PromoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/cabang': typeof AdminCabangRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/kategori-artikel': typeof AdminKategoriArtikelRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/tim': typeof AdminTimRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin': typeof AdminIndexRoute
  '/artikel': typeof ArtikelIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cabang': typeof CabangRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/promo': typeof PromoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/cabang': typeof AdminCabangRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/kategori-artikel': typeof AdminKategoriArtikelRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/tim': typeof AdminTimRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cabang'
    | '/faq'
    | '/kontak'
    | '/layanan'
    | '/promo'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/cabang'
    | '/admin/faq'
    | '/admin/kategori'
    | '/admin/kategori-artikel'
    | '/admin/layanan'
    | '/admin/media'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/promo'
    | '/admin/testimoni'
    | '/admin/tim'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/admin/'
    | '/artikel/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cabang'
    | '/faq'
    | '/kontak'
    | '/layanan'
    | '/promo'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/cabang'
    | '/admin/faq'
    | '/admin/kategori'
    | '/admin/kategori-artikel'
    | '/admin/layanan'
    | '/admin/media'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/promo'
    | '/admin/testimoni'
    | '/admin/tim'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/admin'
    | '/artikel'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cabang'
    | '/faq'
    | '/kontak'
    | '/layanan'
    | '/promo'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/cabang'
    | '/admin/faq'
    | '/admin/kategori'
    | '/admin/kategori-artikel'
    | '/admin/layanan'
    | '/admin/media'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/promo'
    | '/admin/testimoni'
    | '/admin/tim'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/admin/'
    | '/artikel/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CabangRoute: typeof CabangRoute
  FaqRoute: typeof FaqRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  PromoRoute: typeof PromoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabang': {
      id: '/cabang'
      path: '/cabang'
      fullPath: '/cabang'
      preLoaderRoute: typeof CabangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tim': {
      id: '/admin/tim'
      path: '/tim'
      fullPath: '/admin/tim'
      preLoaderRoute: typeof AdminTimRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimoni': {
      id: '/admin/testimoni'
      path: '/testimoni'
      fullPath: '/admin/testimoni'
      preLoaderRoute: typeof AdminTestimoniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produk': {
      id: '/admin/produk'
      path: '/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AdminProdukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesan': {
      id: '/admin/pesan'
      path: '/pesan'
      fullPath: '/admin/pesan'
      preLoaderRoute: typeof AdminPesanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/layanan': {
      id: '/admin/layanan'
      path: '/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof AdminLayananRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategori-artikel': {
      id: '/admin/kategori-artikel'
      path: '/kategori-artikel'
      fullPath: '/admin/kategori-artikel'
      preLoaderRoute: typeof AdminKategoriArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategori': {
      id: '/admin/kategori'
      path: '/kategori'
      fullPath: '/admin/kategori'
      preLoaderRoute: typeof AdminKategoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cabang': {
      id: '/admin/cabang'
      path: '/cabang'
      fullPath: '/admin/cabang'
      preLoaderRoute: typeof AdminCabangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminCabangRoute: typeof AdminCabangRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminKategoriRoute: typeof AdminKategoriRoute
  AdminKategoriArtikelRoute: typeof AdminKategoriArtikelRoute
  AdminLayananRoute: typeof AdminLayananRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminPesanRoute: typeof AdminPesanRoute
  AdminProdukRoute: typeof AdminProdukRoute
  AdminPromoRoute: typeof AdminPromoRoute
  AdminTestimoniRoute: typeof AdminTestimoniRoute
  AdminTimRoute: typeof AdminTimRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtikelRoute: AdminArtikelRoute,
  AdminCabangRoute: AdminCabangRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminKategoriRoute: AdminKategoriRoute,
  AdminKategoriArtikelRoute: AdminKategoriArtikelRoute,
  AdminLayananRoute: AdminLayananRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminPesanRoute: AdminPesanRoute,
  AdminProdukRoute: AdminProdukRoute,
  AdminPromoRoute: AdminPromoRoute,
  AdminTestimoniRoute: AdminTestimoniRoute,
  AdminTimRoute: AdminTimRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CabangRoute: CabangRoute,
  FaqRoute: FaqRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  PromoRoute: PromoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
